openapi: 3.0.3
info:
  title: tunnel operate - OpenAPI 3.0
  description: |-
    This is tunnel operate OpenAPI.
  version: 1.0.0
components:
  schemas:
    NeWebProxyCreateDto:
      type: object
      properties:
        neId:
          type: string
          description: 网元ID
    NeWebProxyCreateResponseDto:
      type: object
      properties:
        neId:
          type: string
          description: 网元ID
        neProxySessionId:
          type: string
          description: 网元代理会话ID
        targetPort:
          type: integer
          description: 目标端口
        ssl:
          type: boolean
          description: 是否开启SSL
